GET http://localhost:3000
###
POST http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "todo" : "Belajar CSS"
}
###
PUT http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "id" : 1,
  "todo" : "Belajar JS"
}
###
DELETE http://localhost:3000
Content-Type: application/json
Accept: application/json

{
  "id" : 0
}